version: '2.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"
    networks:
    - private
  
  kafka:
    image: wurstmeister/kafka
    env_file:
    - kafka/kafka-variables.env
    depends_on:
    - zookeeper
    networks:
    - private
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'
  
  consumer:
    build:
      context: consumer
    networks:
    - private
    depends_on: 
    - kafka

networks:
  private: